export const SOCKET_EVENTS = Object.freeze({
  STATE_SNAPSHOT: "state-snapshot",
  ROOM_STATE: "room-state",
  PARTICIPANT_JOINED: "participant-joined",
  PROBLEM_SUBMITTED: "problem-submitted",
  PARTICIPANT_STATUS_CHANGED: "participant-status-changed",
  ALL_PARTICIPANTS_READY: "all-participants-ready",
  YOUR_GROUP_ASSIGNED: "your-group-assigned",
  YOUR_SESSION_RESTORED: "your-session-restored",
  GROUPS_ASSIGNED: "groups-assigned",
  GAME_STARTED: "game-started",
  GAME_PAUSED: "game-paused",
  GAME_RESUMED: "game-resumed",
  TURN_STARTED: "turn-started",
  CARDS_REVEALED: "cards-revealed",
  TURN_COMPLETED: "turn-completed",
  GAME_FINISHED: "game-finished",
  SERVER_ERROR: "server-error",
});
